### ISSUE TITLE
Week 1 Report

### ISSUE THREAD

**Issue by yaksoo39** [ojs8139/BDAI-training#2]
Your weekly reports should be considered a place where you can organize the work that you did that week.  This should include actual issues/subjects that you reviewed/studied, question that came up that you should follow-up with and anything else that will help you assimilate the subjects of that week.

It also allows us to monitor your progress and give you feedback and guidelines.  

Please do not neglect this very important activity!

**Comment by ojs8139** [comment]
I fix week1 report just now. please review
Thank you.

**Comment by yaksoo39** [comment]
Great.  Glad to see you get to it.
